/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.GrupoBL;
import Controlador.UsuarioBL;
import Modelo.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ronie Paolo
 */
public class ManejoGrupos extends javax.swing.JInternalFrame {

    private int idGrupoSel = -1;
    private int idUsuSel = -1;
    private GrupoBL accesoGrupo = new GrupoBL();
    private UsuarioBL accesoUser = new UsuarioBL();

    public enum estado {
        Inicial, SelecGrupo, Guardar, Modificar, NuevoGrupo
    }

    public ManejoGrupos() {
        initComponents();
        txtNombre.setEnabled(false);
        DefaultTableModel modelo;
        modelo = accesoGrupo.listaTotalGrupo();
        tableGrupos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnAsignarUsr = new javax.swing.JButton();
        pnlGrupo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGrupos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        TxtNomGrupo = new javax.swing.JTextField();
        BtnBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnBuscaUsuario = new javax.swing.JButton();
        lblIcon = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));

        tableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido Paterno", "Apellido Materno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUsuariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableUsuarios);

        jLabel1.setText("Usuarios del grupo:");

        btnEliminar.setText("Eliminar usuario seleccionado");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        btnAsignarUsr.setText("Agregar usuario al grupo seleccionado");
        btnAsignarUsr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAsignarUsrMouseClicked(evt);
            }
        });
        btnAsignarUsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarUsrActionPerformed(evt);
            }
        });

        pnlGrupo.setBackground(new java.awt.Color(255, 255, 255));
        pnlGrupo.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupos"));

        tableGrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableGrupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableGruposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableGrupos);

        jLabel2.setText("Nombre: ");

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGrupoLayout = new javax.swing.GroupLayout(pnlGrupo);
        pnlGrupo.setLayout(pnlGrupoLayout);
        pnlGrupoLayout.setHorizontalGroup(
            pnlGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGrupoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNomGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlGrupoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlGrupoLayout.setVerticalGroup(
            pnlGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGrupoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNomGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscar)
                    .addComponent(jLabel2))
                .addContainerGap(456, Short.MAX_VALUE))
            .addGroup(pnlGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlGrupoLayout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));

        jLabel3.setText("Codigo:");

        jLabel4.setText("Nombre:");

        btnBuscaUsuario.setText("Buscar Usuario");
        btnBuscaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscaUsuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBuscaUsuario)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addComponent(txtCodigo))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnBuscaUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grupo.png"))); // NOI18N

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(btnAsignarUsr))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblIcon))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIcon)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAsignarUsr)
                    .addComponent(btnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableGruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableGruposMouseClicked
        // TODO add your handling code here:
        int index = tableGrupos.getSelectedRow();
        idGrupoSel = (int) tableGrupos.getValueAt(index, 0);
        try {
            DefaultTableModel modeloU = accesoGrupo.listaUsuariosXGrupo(idGrupoSel);
            tableUsuarios.setModel(modeloU);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tableGruposMouseClicked

    private void btnBuscaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscaUsuarioMouseClicked
        // TODO add your handling code here:
        if (txtCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingresar un codigo");
            return;
        }
        int codigo = Integer.parseInt(txtCodigo.getText());
        Usuario u = accesoUser.buscarUsuarioXcodigo(codigo);
        if (u != null) {
            txtNombre.setText(u.getNombre()+' '+u.getaPaterno()+' '+u.getaMaterno());
            idUsuSel=u.getnEntidad();
            System.out.println(u.getnEntidad());
        } else {
            txtNombre.setText("NO ENCONTRADO");
        }
    }//GEN-LAST:event_btnBuscaUsuarioMouseClicked

    private void btnAsignarUsrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsignarUsrMouseClicked
        // TODO add your handling code here:  
        if (!txtNombre.getText().equals("NO ENCONTRADO") && !txtNombre.getText().equals("")) {
            if (idGrupoSel != -1) {
                //int idUsu = Integer.parseInt(txtCodigo.getText());
                System.out.println(idUsuSel);
                accesoGrupo.asignarUsuario(idUsuSel, idGrupoSel);
                try{
                    DefaultTableModel modeloU = accesoGrupo.listaUsuariosXGrupo(idGrupoSel);
                    tableUsuarios.setModel(modeloU);
                    JOptionPane.showMessageDialog(null, "Usuario Seleccionado");
                }catch(Exception e){}
            } else {
                JOptionPane.showMessageDialog(null, "Seleccionar un grupo");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Usuario no valido");
            return;
        }
    }//GEN-LAST:event_btnAsignarUsrMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        int index = tableUsuarios.getSelectedRow();
        
        UsuarioBL uBL= new UsuarioBL();
        Usuario u=uBL.buscarUsuarioXcodigo((int) tableUsuarios.getValueAt(index, 0));
        idUsuSel=u.getnEntidad();
        if(idGrupoSel==-1)
            JOptionPane.showMessageDialog(null, "Seleccionar un grupo!");
        if(idUsuSel==-1)
            JOptionPane.showMessageDialog(null, "Seleccionar un usuario!");
        if(idUsuSel!=-1 && idGrupoSel!=-1){
            int reply = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar este usuario del grupo?", "Aviso", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                System.out.println(idUsuSel);
                System.out.println(idGrupoSel);
                accesoGrupo.eliminarUsuarioGrupo(idUsuSel, idGrupoSel);
                idUsuSel=-1;
                DefaultTableModel modeloU;
                try {
                    modeloU = accesoGrupo.listaUsuariosXGrupo(idGrupoSel);
                    tableUsuarios.setModel(modeloU);
                } catch (SQLException ex) {
                    Logger.getLogger(ManejoGrupos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else return;
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void tableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUsuariosMouseClicked
        // TODO add your handling code here:
        int index = tableUsuarios.getSelectedRow();
        idUsuSel = (int) tableUsuarios.getValueAt(index, 0);
    }//GEN-LAST:event_tableUsuariosMouseClicked

    private void btnAsignarUsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarUsrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsignarUsrActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
        int encontrado=-1;
        for(int i=0;i<tableGrupos.getRowCount();i++){
            System.out.println(tableGrupos.getValueAt(i,1));
            if(tableGrupos.getValueAt(i,1).equals(TxtNomGrupo.getText())){
                encontrado=i;
            }
        }
        if(encontrado==-1){
            JOptionPane.showMessageDialog(null, "Grupo no encontrado");
            return;
        }
        tableGrupos.setRowSelectionInterval(encontrado, encontrado);
        int index = tableGrupos.getSelectedRow();
        idGrupoSel = (int) tableGrupos.getValueAt(index, 0);
        try {
            DefaultTableModel modeloU = accesoGrupo.listaUsuariosXGrupo(idGrupoSel);
            tableUsuarios.setModel(modeloU);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_BtnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ManejoGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ManejoGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ManejoGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ManejoGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ManejoGrupos().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JTextField TxtNomGrupo;
    private javax.swing.JButton btnAsignarUsr;
    private javax.swing.JButton btnBuscaUsuario;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlGrupo;
    private javax.swing.JTable tableGrupos;
    private javax.swing.JTable tableUsuarios;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
